# Generated by Django 3.2.9 on 2021-11-20 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeUC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_atividade', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('plano', models.FileField(upload_to='plano')),
                ('complemento_1', models.FileField(upload_to='complemento')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='uc.uc')),
            ],
        ),
    ]
