# Generated by Django 3.2.9 on 2021-11-22 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uc', '0003_comentarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentarios',
        ),
    ]
