# Generated by Django 3.2.9 on 2021-11-22 03:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('uc', '0007_coment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
                ('nome_atividade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='uc.atividadeuc')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario')),
            ],
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='nome_atividade',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Coment',
        ),
        migrations.DeleteModel(
            name='Comentarios',
        ),
    ]
