# Generated by Django 3.2.9 on 2021-11-23 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aula',
            new_name='Atividade',
        ),
        migrations.RenameModel(
            old_name='Curso',
            new_name='UC',
        ),
    ]
