# Generated by Django 3.2.9 on 2021-11-24 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_uc_obs_docente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uc',
            name='obs_docente',
        ),
    ]
