# Generated by Django 3.2.9 on 2021-11-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_remove_uc_obs_docente'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='obs_docente',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
