# Generated by Django 3.2.9 on 2021-11-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_atividade_obs_docente'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='plano',
            field=models.FileField(blank=True, null=True, upload_to='planos'),
        ),
    ]
